/**
 * recovery-data.js
 * Automatic workspace recovery and restoration tools.
 */

window.TACHOTASKS_ORIGINAL_BACKUP = {
  "tasks": [
    {
      "recurring": null,
      "plannedTime": null,
      "tags": [],
      "completed": false,
      "parentTaskId": null,
      "plannedDate": null,
      "title": "MP 1.2",
      "dueTime": null,
      "sectionId": "sec-id-mtb85os1-jso47x",
      "completedAt": null,
      "description": "",
      "priority": "P3",
      "createdAt": "2026-08-27T19:29:54.383Z",
      "id": "id-mtbx30zz-0tfze4",
      "projectId": null,
      "dueDate": "2026-09-08",
      "profileId": "profile-school",
      "updatedAt": "2026-08-27T19:29:54.383Z"
    },
    {
      "tags": [],
      "plannedTime": null,
      "profileId": "profile-school",
      "plannedDate": null,
      "projectId": null,
      "completedAt": null,
      "dueTime": null,
      "createdAt": "2026-08-27T19:30:59.893Z",
      "priority": "P3",
      "description": "",
      "parentTaskId": null,
      "id": "id-mtbx4fjp-1bzxza",
      "sectionId": "sec-id-mtb85os1-jso47x",
      "title": "MP 1.3",
      "recurring": null,
      "dueDate": "2026-09-15",
      "completed": false,
      "updatedAt": "2026-08-27T19:30:59.893Z"
    },
    {
      "completedAt": null,
      "projectId": null,
      "createdAt": "2026-08-27T21:19:13.735Z",
      "plannedDate": null,
      "id": "id-mtc0zm87-bjsiml",
      "dueDate": "2026-09-22",
      "profileId": "profile-school",
      "tags": [],
      "plannedTime": null,
      "title": "EXTRA CREDIT Syllabus Test",
      "priority": "P1",
      "completed": false,
      "recurring": null,
      "dueTime": "23:59",
      "sectionId": "sec-id-mtb85rxs-dl8g2h",
      "parentTaskId": null,
      "description": "",
      "updatedAt": "2026-09-01T21:40:15.776Z"
    },
    {
      "profileId": "profile-school",
      "tags": [],
      "createdAt": "2026-08-27T21:19:40.902Z",
      "parentTaskId": null,
      "description": "",
      "dueTime": "23:59",
      "projectId": null,
      "priority": "P1",
      "sectionId": "sec-id-mtb85rxs-dl8g2h",
      "title": "EXTRA CREDIT - ECON 302 Pretest",
      "completedAt": null,
      "dueDate": "2026-09-22",
      "completed": false,
      "plannedTime": null,
      "id": "id-mtc1076u-e6uomf",
      "recurring": null,
      "updatedAt": "2026-08-27T21:19:40.902Z"
    },
    {
      "title": "Lesson 1 Graded Quiz",
      "dueTime": "23:59",
      "tags": [],
      "priority": "P3",
      "parentTaskId": null,
      "profileId": "profile-school",
      "description": "",
      "createdAt": "2026-08-27T21:20:22.913Z",
      "projectId": null,
      "id": "id-mtc113lt-vs0pse",
      "dueDate": "2026-09-22",
      "plannedDate": null,
      "sectionId": "sec-id-mtb85rxs-dl8g2h",
      "completedAt": null,
      "recurring": null,
      "plannedTime": null,
      "completed": false,
      "updatedAt": "2026-08-27T21:20:22.913Z"
    },
    {
      "id": "id-mtc11t5a-y2rhh7",
      "projectId": null,
      "description": "",
      "createdAt": "2026-08-27T21:20:56.014Z",
      "dueDate": "2026-09-22",
      "parentTaskId": null,
      "profileId": "profile-school",
      "recurring": null,
      "plannedTime": null,
      "dueTime": "23:59",
      "priority": "P3",
      "completed": false,
      "tags": [],
      "completedAt": null,
      "title": "Lesson 2 Graded Quiz",
      "sectionId": "sec-id-mtb85rxs-dl8g2h",
      "plannedDate": null,
      "updatedAt": "2026-08-27T21:20:56.014Z"
    },
    {
      "recurring": null,
      "dueDate": "2026-10-06",
      "completedAt": null,
      "completed": false,
      "id": "id-mtc12dlm-ikltou",
      "title": "Lesson 3 Graded Quiz",
      "plannedTime": null,
      "sectionId": "sec-id-mtb85rxs-dl8g2h",
      "parentTaskId": null,
      "dueTime": "23:59",
      "createdAt": "2026-08-27T21:21:22.522Z",
      "priority": "P4",
      "projectId": null,
      "profileId": "profile-school",
      "description": "",
      "tags": [],
      "updatedAt": "2026-08-27T21:21:22.522Z"
    },
    {
      "completed": false,
      "recurring": null,
      "plannedTime": null,
      "priority": "P4",
      "dueTime": "23:59",
      "completedAt": null,
      "sectionId": "sec-id-mtb85rxs-dl8g2h",
      "tags": [],
      "title": "Lesson 4 Graded Quiz",
      "projectId": null,
      "createdAt": "2026-08-27T21:21:38.440Z",
      "parentTaskId": null,
      "description": "",
      "id": "id-mtc12pvs-6znbed",
      "profileId": "profile-school",
      "dueDate": "2026-10-27",
      "updatedAt": "2026-08-27T21:21:38.440Z"
    },
    {
      "title": "Lesson 5 Graded Quiz",
      "description": "",
      "tags": [],
      "dueDate": "2026-11-17",
      "projectId": null,
      "createdAt": "2026-08-27T21:21:47.583Z",
      "parentTaskId": null,
      "priority": "P4",
      "profileId": "profile-school",
      "plannedTime": null,
      "recurring": null,
      "dueTime": "23:59",
      "completed": false,
      "id": "id-mtc12wxr-c2mg1w",
      "sectionId": "sec-id-mtb85rxs-dl8g2h",
      "completedAt": null,
      "updatedAt": "2026-08-27T21:21:47.583Z"
    },
    {
      "createdAt": "2026-08-27T21:22:11.142Z",
      "projectId": null,
      "dueDate": "2026-12-08",
      "profileId": "profile-school",
      "description": "",
      "parentTaskId": null,
      "recurring": null,
      "priority": "P4",
      "completedAt": null,
      "completed": false,
      "id": "id-mtc13f46-vxi89c",
      "dueTime": "23:59",
      "tags": [],
      "sectionId": "sec-id-mtb85rxs-dl8g2h",
      "title": "Lesson 6 Graded Quiz",
      "plannedTime": null,
      "updatedAt": "2026-08-27T21:22:11.142Z"
    },
    {
      "parentTaskId": null,
      "sectionId": "sec-id-mtb85rxs-dl8g2h",
      "dueDate": "2026-12-15",
      "id": "id-mtc13orz-cho44b",
      "completed": false,
      "description": "",
      "recurring": null,
      "profileId": "profile-school",
      "dueTime": "23:59",
      "completedAt": null,
      "tags": [],
      "createdAt": "2026-08-27T21:22:23.663Z",
      "projectId": null,
      "plannedTime": null,
      "title": "Lesson 7 Graded Quiz",
      "priority": "P4",
      "updatedAt": "2026-08-27T21:22:23.663Z"
    },
    {
      "id": "id-mth02sec-qcygmc",
      "title": "Add midterm and final dates into calendar",
      "description": "",
      "priority": "P4",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mtciwu6m-bjdwng",
      "parentTaskId": null,
      "dueDate": null,
      "dueTime": null,
      "recurring": null,
      "completed": false,
      "completedAt": null,
      "createdAt": "2026-08-31T08:52:32.964Z",
      "updatedAt": "2026-08-31T08:52:32.964Z",
      "profileId": "profile-personal",
      "plannedTime": null
    },
    {
      "plannedDate": null,
      "id": "id-mth02xay-lat1ns",
      "plannedTime": null,
      "priority": "P4",
      "recurring": null,
      "completed": false,
      "completedAt": null,
      "updatedAt": "2026-08-31T09:01:54.238Z",
      "dueTime": null,
      "tags": [],
      "profileId": "profile-personal",
      "title": "Add Information to Contacts",
      "description": "https://www.icloud.com/contacts/",
      "dueDate": null,
      "createdAt": "2026-08-31T08:52:39.322Z",
      "sectionId": "sec-id-mtciwu6m-bjdwng",
      "parentTaskId": null,
      "projectId": null
    },
    {
      "id": "id-mth03b25-0rur1v",
      "title": "Sort Google Drive",
      "description": "",
      "priority": "P4",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mtciwu6m-bjdwng",
      "parentTaskId": null,
      "dueDate": null,
      "dueTime": null,
      "recurring": null,
      "completed": false,
      "completedAt": null,
      "createdAt": "2026-08-31T08:52:57.149Z",
      "updatedAt": "2026-08-31T08:52:57.149Z",
      "profileId": "profile-personal",
      "plannedTime": null
    },
    {
      "id": "id-mth03ig0-27zux5",
      "title": "Sort Gmail and Outlook",
      "description": "",
      "priority": "P4",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mtciwu6m-bjdwng",
      "parentTaskId": null,
      "dueDate": null,
      "dueTime": null,
      "recurring": null,
      "completed": false,
      "completedAt": null,
      "createdAt": "2026-08-31T08:53:06.720Z",
      "updatedAt": "2026-08-31T08:53:06.720Z",
      "profileId": "profile-personal",
      "plannedTime": null
    },
    {
      "id": "id-mth0rihr-dnu4yf",
      "title": "Microtheme 1",
      "description": "",
      "priority": "P2",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mtb85ygc-akym7u",
      "parentTaskId": null,
      "dueDate": "2026-09-08",
      "dueTime": "08:00",
      "recurring": null,
      "completed": false,
      "completedAt": null,
      "createdAt": "2026-08-31T09:11:46.526Z",
      "updatedAt": "2026-09-01T06:12:39.550Z",
      "profileId": "profile-school",
      "plannedDate": null,
      "plannedTime": null
    },
    {
      "id": "id-mth0v4fz-63yn7s",
      "title": "Macrotheme 1, draft 2",
      "description": "",
      "priority": "P4",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mtb85ygc-akym7u",
      "parentTaskId": null,
      "dueDate": "2026-09-14",
      "dueTime": "08:00",
      "recurring": null,
      "completed": false,
      "completedAt": null,
      "createdAt": "2026-08-31T09:14:34.943Z",
      "updatedAt": "2026-08-31T09:15:45.860Z",
      "profileId": "profile-school",
      "plannedDate": null,
      "plannedTime": null
    },
    {
      "id": "id-mth0vnco-icc4bk",
      "title": "Microtheme 2",
      "description": "",
      "priority": "P4",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mtb85ygc-akym7u",
      "parentTaskId": null,
      "dueDate": "2026-09-21",
      "dueTime": "08:00",
      "recurring": null,
      "completed": false,
      "completedAt": null,
      "createdAt": "2026-08-31T09:14:59.448Z",
      "updatedAt": "2026-08-31T09:15:52.288Z",
      "profileId": "profile-school",
      "plannedDate": null,
      "plannedTime": null
    },
    {
      "id": "id-mth0vxc3-xtpl8j",
      "title": "Macrotheme 1, final draft",
      "description": "",
      "priority": "P4",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mtb85ygc-akym7u",
      "parentTaskId": null,
      "dueDate": "2026-09-28",
      "dueTime": "08:00",
      "recurring": null,
      "completed": false,
      "completedAt": null,
      "createdAt": "2026-08-31T09:15:12.387Z",
      "updatedAt": "2026-08-31T09:15:59.539Z",
      "profileId": "profile-school",
      "plannedDate": null,
      "plannedTime": null
    },
    {
      "id": "id-mth0xo0o-2yn0z5",
      "title": "Macrotheme 2, draft 1",
      "description": "",
      "priority": "P4",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mtb85ygc-akym7u",
      "parentTaskId": null,
      "dueDate": "2026-10-05",
      "dueTime": "08:00",
      "recurring": null,
      "completed": false,
      "completedAt": null,
      "createdAt": "2026-08-31T09:16:33.624Z",
      "updatedAt": "2026-08-31T09:18:07.147Z",
      "profileId": "profile-school",
      "plannedDate": null,
      "plannedTime": null
    },
    {
      "id": "id-mth0xwmr-ytcgmm",
      "title": "Microtheme 3",
      "description": "",
      "priority": "P4",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mtb85ygc-akym7u",
      "parentTaskId": null,
      "dueDate": "2026-10-12",
      "dueTime": "08:00",
      "recurring": null,
      "completed": false,
      "completedAt": null,
      "createdAt": "2026-08-31T09:16:44.787Z",
      "updatedAt": "2026-08-31T09:16:44.787Z",
      "profileId": "profile-school",
      "plannedTime": null
    },
    {
      "id": "id-mth0y4u8-0unjoo",
      "title": "Macrotheme 2, draft 2",
      "description": "",
      "priority": "P4",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mtb85ygc-akym7u",
      "parentTaskId": null,
      "dueDate": "2026-10-19",
      "dueTime": "08:00",
      "recurring": null,
      "completed": false,
      "completedAt": null,
      "createdAt": "2026-08-31T09:16:55.424Z",
      "updatedAt": "2026-08-31T09:16:55.424Z",
      "profileId": "profile-school",
      "plannedTime": null
    },
    {
      "id": "id-mth0ycjm-287cy7",
      "title": "Microtheme 4",
      "description": "",
      "priority": "P4",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mtb85ygc-akym7u",
      "parentTaskId": null,
      "dueDate": "2026-10-26",
      "dueTime": "08:00",
      "recurring": null,
      "completed": false,
      "completedAt": null,
      "createdAt": "2026-08-31T09:17:05.410Z",
      "updatedAt": "2026-08-31T09:17:05.410Z",
      "profileId": "profile-school",
      "plannedTime": null
    },
    {
      "id": "id-mth0zjwx-xwstoo",
      "title": "Macrotheme 2, final draft",
      "description": "",
      "priority": "P4",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mtb85ygc-akym7u",
      "parentTaskId": null,
      "dueDate": "2026-11-02",
      "dueTime": "08:00",
      "recurring": null,
      "completed": false,
      "completedAt": null,
      "createdAt": "2026-08-31T09:18:01.617Z",
      "updatedAt": "2026-08-31T09:18:01.617Z",
      "profileId": "profile-school",
      "plannedTime": null
    },
    {
      "id": "id-mth100cu-dahmd7",
      "title": "Macrotheme 3, draft 1",
      "description": "",
      "priority": "P4",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mtb85ygc-akym7u",
      "parentTaskId": null,
      "dueDate": "2026-11-09",
      "dueTime": "08:00",
      "recurring": null,
      "completed": false,
      "completedAt": null,
      "createdAt": "2026-08-31T09:18:22.926Z",
      "updatedAt": "2026-08-31T09:18:22.926Z",
      "profileId": "profile-school",
      "plannedTime": null
    },
    {
      "id": "id-mth10csd-gu2ri3",
      "title": "Microtheme 5",
      "description": "",
      "priority": "P4",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mtb85ygc-akym7u",
      "parentTaskId": null,
      "dueDate": "2026-11-16",
      "dueTime": "08:00",
      "recurring": null,
      "completed": false,
      "completedAt": null,
      "createdAt": "2026-08-31T09:18:39.037Z",
      "updatedAt": "2026-08-31T09:18:39.037Z",
      "profileId": "profile-school",
      "plannedTime": null
    },
    {
      "id": "id-mth10t2k-d7u8fs",
      "title": "Macrotheme 3, draft 2",
      "description": "",
      "priority": "P4",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mtb85ygc-akym7u",
      "parentTaskId": null,
      "dueDate": "2026-11-30",
      "dueTime": "08:00",
      "recurring": null,
      "completed": false,
      "completedAt": null,
      "createdAt": "2026-08-31T09:19:00.140Z",
      "updatedAt": "2026-08-31T09:19:00.140Z",
      "profileId": "profile-school",
      "plannedTime": null
    },
    {
      "id": "id-mth11ijm-h95d82",
      "title": "Microtheme 6",
      "description": "",
      "priority": "P4",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mtb85ygc-akym7u",
      "parentTaskId": null,
      "dueDate": "2026-12-07",
      "dueTime": "08:00",
      "recurring": null,
      "completed": false,
      "completedAt": null,
      "createdAt": "2026-08-31T09:19:33.154Z",
      "updatedAt": "2026-08-31T09:19:33.154Z",
      "profileId": "profile-school",
      "plannedTime": null
    },
    {
      "id": "id-mth11vel-ose2w4",
      "title": "Macrotheme 3, final draft",
      "description": "",
      "priority": "P4",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mtb85ygc-akym7u",
      "parentTaskId": null,
      "dueDate": "2026-12-17",
      "dueTime": "08:00",
      "recurring": null,
      "completed": false,
      "completedAt": null,
      "createdAt": "2026-08-31T09:19:49.821Z",
      "updatedAt": "2026-08-31T09:19:49.821Z",
      "profileId": "profile-school",
      "plannedTime": null
    },
    {
      "id": "id-mth13uhm-49f9h6",
      "title": "Work on Google Sheet and SORF",
      "description": "",
      "priority": "P4",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mth13maq-2e0emi",
      "parentTaskId": null,
      "dueDate": "2026-09-05",
      "dueTime": "15:00",
      "recurring": null,
      "completed": false,
      "completedAt": null,
      "createdAt": "2026-08-31T09:21:21.946Z",
      "updatedAt": "2026-09-03T23:58:42.252Z",
      "profileId": "profile-work",
      "plannedDate": null,
      "plannedTime": null
    },
    {
      "id": "id-mth16tpl-xd5bdo",
      "title": "Regular Expressions and DFAs",
      "description": "",
      "priority": "P2",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mtb85m9m-2q50tr",
      "parentTaskId": null,
      "dueDate": "2026-09-08",
      "dueTime": "21:15",
      "recurring": null,
      "completed": false,
      "completedAt": null,
      "createdAt": "2026-08-31T09:23:40.905Z",
      "updatedAt": "2026-08-31T09:23:40.905Z",
      "profileId": "profile-school",
      "plannedTime": null
    },
    {
      "id": "id-mtho3lqf-l8zefi",
      "title": "Homework 1",
      "description": "",
      "priority": "P4",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mtb85utq-ejgqrb",
      "parentTaskId": null,
      "dueDate": "2026-09-14",
      "dueTime": "23:59",
      "recurring": null,
      "completed": false,
      "completedAt": null,
      "createdAt": "2026-08-31T20:05:01.767Z",
      "updatedAt": "2026-08-31T20:05:01.767Z",
      "profileId": "profile-school",
      "plannedTime": null
    },
    {
      "id": "id-mtho3x1f-1r30lj",
      "title": "Homework 2",
      "description": "",
      "priority": "P4",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mtb85utq-ejgqrb",
      "parentTaskId": null,
      "dueDate": "2026-09-14",
      "dueTime": "23:59",
      "recurring": null,
      "completed": false,
      "completedAt": null,
      "createdAt": "2026-08-31T20:05:16.419Z",
      "updatedAt": "2026-08-31T20:05:16.419Z",
      "profileId": "profile-school",
      "plannedTime": null
    },
    {
      "id": "id-mtho47h5-9bojlt",
      "title": "Homework 3",
      "description": "",
      "priority": "P4",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mtb85utq-ejgqrb",
      "parentTaskId": null,
      "dueDate": "2026-09-21",
      "dueTime": "23:59",
      "recurring": null,
      "completed": false,
      "completedAt": null,
      "createdAt": "2026-08-31T20:05:29.945Z",
      "updatedAt": "2026-08-31T20:05:29.945Z",
      "profileId": "profile-school",
      "plannedTime": null
    },
    {
      "id": "id-mtho4gun-4sxg9j",
      "title": "Homework 4",
      "description": "",
      "priority": "P4",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mtb85utq-ejgqrb",
      "parentTaskId": null,
      "dueDate": "2026-09-28",
      "dueTime": "23:59",
      "recurring": null,
      "completed": false,
      "completedAt": null,
      "createdAt": "2026-08-31T20:05:42.095Z",
      "updatedAt": "2026-08-31T20:05:42.095Z",
      "profileId": "profile-school",
      "plannedTime": null
    },
    {
      "id": "id-mtho4lcw-1gwx13",
      "title": "Homework 5",
      "description": "",
      "priority": "P4",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mtb85utq-ejgqrb",
      "parentTaskId": null,
      "dueDate": "2026-10-05",
      "dueTime": "23:59",
      "recurring": null,
      "completed": false,
      "completedAt": null,
      "createdAt": "2026-08-31T20:05:47.936Z",
      "updatedAt": "2026-08-31T20:05:47.936Z",
      "profileId": "profile-school",
      "plannedTime": null
    },
    {
      "id": "id-mtho4rz1-0kivo1",
      "title": "Homework 6",
      "description": "",
      "priority": "P4",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mtb85utq-ejgqrb",
      "parentTaskId": null,
      "dueDate": "2026-10-19",
      "dueTime": "23:59",
      "recurring": null,
      "completed": false,
      "completedAt": null,
      "createdAt": "2026-08-31T20:05:56.509Z",
      "updatedAt": "2026-08-31T20:05:56.509Z",
      "profileId": "profile-school",
      "plannedTime": null
    },
    {
      "id": "id-mtho4woq-l0sieo",
      "title": "Homework 7",
      "description": "",
      "priority": "P4",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mtb85utq-ejgqrb",
      "parentTaskId": null,
      "dueDate": "2026-10-26",
      "dueTime": "23:59",
      "recurring": null,
      "completed": false,
      "completedAt": null,
      "createdAt": "2026-08-31T20:06:02.618Z",
      "updatedAt": "2026-08-31T20:06:02.618Z",
      "profileId": "profile-school",
      "plannedTime": null
    },
    {
      "id": "id-mtho4zwi-8yrshz",
      "title": "Homework 8",
      "description": "",
      "priority": "P4",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mtb85utq-ejgqrb",
      "parentTaskId": null,
      "dueDate": "2026-11-02",
      "dueTime": "23:59",
      "recurring": null,
      "completed": false,
      "completedAt": null,
      "createdAt": "2026-08-31T20:06:06.786Z",
      "updatedAt": "2026-08-31T20:06:06.786Z",
      "profileId": "profile-school",
      "plannedTime": null
    },
    {
      "id": "id-mtho55r0-5rrs9n",
      "title": "Homework 9",
      "description": "",
      "priority": "P4",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mtb85utq-ejgqrb",
      "parentTaskId": null,
      "dueDate": "2026-11-09",
      "dueTime": "23:59",
      "recurring": null,
      "completed": false,
      "completedAt": null,
      "createdAt": "2026-08-31T20:06:14.364Z",
      "updatedAt": "2026-08-31T20:06:14.364Z",
      "profileId": "profile-school",
      "plannedTime": null
    },
    {
      "id": "id-mtho5c8o-rz913w",
      "title": "Homework 10",
      "description": "",
      "priority": "P4",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mtb85utq-ejgqrb",
      "parentTaskId": null,
      "dueDate": "2026-11-30",
      "dueTime": "23:59",
      "recurring": null,
      "completed": false,
      "completedAt": null,
      "createdAt": "2026-08-31T20:06:22.776Z",
      "updatedAt": "2026-08-31T20:06:22.776Z",
      "profileId": "profile-school",
      "plannedTime": null
    },
    {
      "id": "id-mtho5hpq-nk2pnm",
      "title": "Homework 11",
      "description": "",
      "priority": "P4",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mtb85utq-ejgqrb",
      "parentTaskId": null,
      "dueDate": "2026-12-07",
      "dueTime": "23:59",
      "recurring": null,
      "completed": false,
      "completedAt": null,
      "createdAt": "2026-08-31T20:06:29.870Z",
      "updatedAt": "2026-08-31T20:06:29.870Z",
      "profileId": "profile-school",
      "plannedTime": null
    }
  ],
  "archivedTasks": [
    {
      "recurring": null,
      "completedAt": "2026-08-29T07:31:22.872Z",
      "completed": true,
      "dueDate": "2026-08-31",
      "sectionId": "sec-id-mtb85ygc-akym7u",
      "plannedTime": null,
      "id": "id-mtc15kgt-615fhr",
      "isCompleting": false,
      "tags": [],
      "priority": "P1",
      "parentTaskId": null,
      "createdAt": "2026-08-27T21:23:51.389Z",
      "completionTimeout": 829,
      "projectId": null,
      "dueTime": "08:00",
      "profileId": "profile-school",
      "description": "",
      "title": "Week 1 Quiz",
      "updatedAt": "2026-08-27T21:23:51.389Z"
    },
    {
      "dueTime": "23:59",
      "description": "",
      "sectionId": "sec-id-mtb85os1-jso47x",
      "parentTaskId": null,
      "recurring": null,
      "completionTimeout": 1166,
      "priority": "P2",
      "completed": true,
      "dueDate": "2026-09-02",
      "plannedTime": null,
      "profileId": "profile-school",
      "id": "id-mtc3452h-5xqio3",
      "completedAt": "2026-08-27T23:44:08.063Z",
      "isCompleting": false,
      "tags": [],
      "projectId": null,
      "title": "HW1: Overview and Syllabus",
      "createdAt": "2026-08-27T22:18:44.009Z",
      "updatedAt": "2026-08-27T22:18:44.009Z"
    },
    {
      "priority": "P1",
      "id": "id-mtc15ckr-rdty6l",
      "sectionId": "sec-id-mtb85ygc-akym7u",
      "completedAt": "2026-09-01T21:30:20.989Z",
      "recurring": null,
      "projectId": null,
      "parentTaskId": null,
      "updatedAt": "2026-09-01T21:30:20.989Z",
      "createdAt": "2026-08-27T21:23:41.163Z",
      "plannedTime": null,
      "title": "Macrotheme 1, draft 1",
      "tags": [],
      "dueDate": "2026-08-31",
      "profileId": "profile-school",
      "description": "",
      "completed": true,
      "dueTime": "08:00",
      "isCompleting": false,
      "completionTimeout": 105
    },
    {
      "updatedAt": "2026-09-01T21:32:42.669Z",
      "parentTaskId": null,
      "sectionId": "sec-id-mtb85os1-jso47x",
      "profileId": "profile-school",
      "completedAt": "2026-09-01T21:32:42.669Z",
      "dueDate": "2026-09-01",
      "description": "",
      "plannedTime": null,
      "plannedDate": null,
      "recurring": null,
      "completed": true,
      "title": "MP 1.1",
      "tags": [],
      "createdAt": "2026-08-27T19:29:33.035Z",
      "isCompleting": false,
      "priority": "P3",
      "dueTime": null,
      "id": "id-mtbx2kiz-zxl91a",
      "projectId": null,
      "completionTimeout": 108
    },
    {
      "id": "id-mti9wma8-etnoe9",
      "title": "Message Vicky about VSA Fam",
      "description": "",
      "priority": "P1",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mtciwu6m-bjdwng",
      "parentTaskId": null,
      "dueDate": "2026-09-01",
      "dueTime": null,
      "recurring": null,
      "completed": true,
      "completedAt": "2026-09-01T21:33:27.161Z",
      "createdAt": "2026-09-01T06:15:27.440Z",
      "updatedAt": "2026-09-01T21:33:27.161Z",
      "profileId": "profile-personal",
      "plannedDate": null,
      "plannedTime": null,
      "isCompleting": false,
      "completionTimeout": 208
    },
    {
      "id": "id-mth03ezv-fqrs3s",
      "title": "Add flights into calendar",
      "description": "",
      "priority": "P4",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mtciwu6m-bjdwng",
      "parentTaskId": null,
      "dueDate": null,
      "dueTime": null,
      "recurring": null,
      "completed": true,
      "completedAt": "2026-09-03T23:34:02.582Z",
      "createdAt": "2026-08-31T08:53:02.251Z",
      "updatedAt": "2026-09-03T23:34:02.582Z",
      "profileId": "profile-personal",
      "plannedTime": null,
      "isCompleting": false,
      "completionTimeout": 229
    },
    {
      "id": "id-mth027fk-eg4dh6",
      "title": "Change github name: web, into tobyyeung.com",
      "description": "",
      "priority": "P4",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mth01i92-ohtyzv",
      "parentTaskId": null,
      "dueDate": null,
      "dueTime": null,
      "recurring": null,
      "completed": true,
      "completedAt": "2026-09-03T23:34:09.328Z",
      "createdAt": "2026-08-31T08:52:05.792Z",
      "updatedAt": "2026-09-03T23:34:09.328Z",
      "profileId": "profile-personal",
      "plannedTime": null,
      "isCompleting": false,
      "completionTimeout": 296
    },
    {
      "completed": true,
      "plannedTime": null,
      "profileId": "profile-personal",
      "priority": "P4",
      "projectId": null,
      "parentTaskId": null,
      "updatedAt": "2026-09-03T23:58:35.278Z",
      "dueDate": "2026-08-31",
      "description": "",
      "plannedDate": null,
      "recurring": null,
      "title": "Fix tobyyeung.com website",
      "sectionId": "sec-id-mtciwu6m-bjdwng",
      "tags": [],
      "dueTime": null,
      "createdAt": "2026-08-29T22:31:45.310Z",
      "id": "id-mteygl9a-b8994h",
      "completedAt": "2026-09-03T23:58:35.278Z",
      "isCompleting": false,
      "completionTimeout": 755
    },
    {
      "id": "id-mtpmbsde-qwb6ra",
      "title": "HW 1.2",
      "description": "",
      "priority": "P1",
      "tags": [],
      "projectId": null,
      "sectionId": "sec-id-mtb85m9m-2q50tr",
      "parentTaskId": null,
      "dueDate": "2027-09-01",
      "dueTime": "21:15",
      "recurring": null,
      "completed": true,
      "completedAt": "2026-09-06T09:37:36.708Z",
      "createdAt": "2026-09-06T09:37:33.794Z",
      "updatedAt": "2026-09-06T09:37:36.708Z",
      "profileId": "profile-school",
      "isCompleting": false,
      "completionTimeout": 409
    },
    {
      "title": "HW 1.1",
      "plannedTime": null,
      "description": "",
      "parentTaskId": null,
      "completedAt": "2026-09-06T09:37:37.320Z",
      "sectionId": "sec-id-mtb85m9m-2q50tr",
      "createdAt": "2026-09-06T09:28:04.501Z",
      "projectId": null,
      "dueTime": "21:15",
      "completed": true,
      "tags": [],
      "profileId": "profile-school",
      "id": "id-mtplzl3p-n8gb1g",
      "updatedAt": "2026-09-06T09:37:37.320Z",
      "recurring": null,
      "priority": "P1",
      "dueDate": "2027-09-01",
      "isCompleting": false,
      "completionTimeout": 412
    }
  ],
  "projects": [
    {
      "id": "proj-id-mtcmb6fa-51931y",
      "name": "Aleago",
      "color": "#5cb8ff",
      "profileId": null,
      "createdAt": "2026-09-01T21:40:41.219Z",
      "updatedAt": "2026-09-01T21:40:41.219Z"
    }
  ],
  "profiles": [
    {
      "id": "all",
      "name": "All",
      "icon": "",
      "image": "assets/brand/logo.png"
    },
    {
      "id": "profile-personal",
      "name": "Personal",
      "icon": "",
      "image": "assets/profiles/personal.png"
    },
    {
      "id": "profile-work",
      "name": "Work",
      "icon": "",
      "image": "assets/profiles/work.png"
    },
    {
      "id": "profile-school",
      "name": "School",
      "icon": "",
      "image": "assets/profiles/school.png"
    }
  ],
  "taskSections": [
    {
      "name": "CS 374",
      "profileId": "profile-school",
      "id": "sec-id-mtb85m9m-2q50tr",
      "link": "https://courses.grainger.illinois.edu/cs374al1/fa2026/index.html"
    },
    {
      "profileId": "profile-school",
      "link": "https://cs340-schatz.com/",
      "id": "sec-id-mtb85os1-jso47x",
      "name": "CS 340"
    },
    {
      "profileId": "profile-school",
      "id": "sec-id-mtb85rxs-dl8g2h",
      "name": "ECON 302",
      "link": "https://canvas.illinois.edu/courses/71913"
    },
    {
      "name": "PLPA 200",
      "id": "sec-id-mtb85ygc-akym7u",
      "profileId": "profile-school",
      "link": "https://canvas.illinois.edu/courses/73614"
    },
    {
      "profileId": "profile-school",
      "id": "sec-id-mtb85utq-ejgqrb",
      "name": "ECON 203",
      "link": "https://canvas.illinois.edu/courses/73838"
    },
    {
      "id": "sec-id-mth13maq-2e0emi",
      "name": "HKSA",
      "link": null,
      "profileId": "profile-work"
    },
    {
      "profileId": "profile-work",
      "id": "sec-id-mtb8639h-nkwxmh",
      "name": "INVITE: Keating"
    },
    {
      "profileId": "profile-work",
      "name": "Technology Services: ICS",
      "id": "sec-id-mtb867vy-z73kim"
    },
    {
      "id": "sec-id-mtciwu6m-bjdwng",
      "link": null,
      "profileId": "profile-personal",
      "name": "Toby"
    },
    {
      "id": "sec-id-mth01i92-ohtyzv",
      "name": "Projects",
      "link": null,
      "profileId": "profile-personal"
    },
    {
      "link": null,
      "profileId": "profile-personal",
      "id": "sec-id-mtcj0cht-62hzvz",
      "name": "Grocery List"
    }
  ],
  "version": "1.0",
  "exportedAt": "2026-09-06T18:41:04.097Z"
};

// Repairs section metadata only. Unlike the full recovery action below, this never replaces tasks.
window.restoreKnownTaskSectionMetadata = async function() {
  const backup = window.TACHOTASKS_ORIGINAL_BACKUP;
  if (!backup || !state || !state.settings) return false;

  const backupSections = Array.isArray(backup.taskSections) ? backup.taskSections : [];
  if (backupSections.length === 0) return false;

  const referencedIds = new Set([...(state.tasks || []), ...(state.archivedTasks || [])]
    .filter(task => task && !task.projectId && task.sectionId && task.sectionId !== 'unsectioned')
    .map(task => task.sectionId));
  if (referencedIds.size === 0) return false;

  const backupById = new Map(backupSections.map(section => [section && section.id, section]).filter(([id]) => Boolean(id)));
  const currentSections = Array.isArray(state.settings.taskSections) ? [...state.settings.taskSections] : [];
  const currentById = new Map(currentSections.map(section => [section && section.id, section]).filter(([id]) => Boolean(id)));
  let changed = false;

  referencedIds.forEach(id => {
    const recovered = backupById.get(id);
    if (!recovered) return;
    const existing = currentById.get(id);
    const hasPlaceholderName = existing && /^Recovered section \d+$/i.test(existing.name || '');
    if (!existing || hasPlaceholderName) {
      const replacement = { ...recovered };
      if (existing) {
        const index = currentSections.findIndex(section => section && section.id === id);
        currentSections[index] = replacement;
      } else {
        currentSections.push(replacement);
      }
      currentById.set(id, replacement);
      changed = true;
    }
  });

  if (!changed) return false;
  state.settings.taskSections = currentSections;
  state.settings.taskSectionsInitialized = true;
  state.settings.updatedAt = new Date().toISOString();
  if (window.api && window.api.saveSettings) await window.api.saveSettings(state.settings);
  return true;
};

window.restoreOriginalWorkspace = async function() {
  if (!window.TACHOTASKS_ORIGINAL_BACKUP) return;
  const backup = window.TACHOTASKS_ORIGINAL_BACKUP;

  state.tasks = Array.isArray(backup.tasks) ? JSON.parse(JSON.stringify(backup.tasks)) : [];
  state.archivedTasks = Array.isArray(backup.archivedTasks) ? JSON.parse(JSON.stringify(backup.archivedTasks)) : [];
  state.projects = Array.isArray(backup.projects) ? JSON.parse(JSON.stringify(backup.projects)) : [];
  state.profiles = Array.isArray(backup.profiles) ? JSON.parse(JSON.stringify(backup.profiles)) : getDefaultProfiles();

  if (!state.settings) state.settings = {};
  state.settings.taskSections = Array.isArray(backup.taskSections) ? JSON.parse(JSON.stringify(backup.taskSections)) : [];
  state.settings.taskSectionsInitialized = true;
  state.settings.profilesInitialized = true;
  state.activeProfileId = 'profile-school';
  state.settings.activeProfileId = 'profile-school';
  state.settings.defaultProfileId = 'profile-personal';

  if (window.api) {
    if (window.api.saveTasks) await window.api.saveTasks(state.tasks);
    if (window.api.saveArchivedTasks) await window.api.saveArchivedTasks(state.archivedTasks);
    if (window.api.saveProjects) await window.api.saveProjects(state.projects);
    if (window.api.saveProfiles) await window.api.saveProfiles(state.profiles);
    if (window.api.saveSettings) await window.api.saveSettings(state.settings);
  }

  if (window.api && window.api.syncPush) {
    try {
      await window.api.syncPush();
    } catch (e) {
      console.warn('syncPush error during recovery:', e);
    }
  } else if (typeof syncToCloud === 'function') {
    syncToCloud();
  }

  const banner = document.getElementById('workspace-recovery-banner');
  if (banner) banner.remove();

  if (typeof setupModeSwitcher === 'function') setupModeSwitcher();
  if (typeof renderSidebarProjects === 'function') renderSidebarProjects();
  if (typeof renderView === 'function') renderView();

  showToast('Restored all 42 tasks and 11 sections successfully!', 'success');
};

